"""Lists of ingredients for most popular cuisines"""

Mexican[
		'red chile sauce',
		'green chile sauce',
		'enchilada sauce',
		'diced green chiles',
		'whole green chiles',
		'chipotle chiles',
		'jalapenos',
		'tomato sauce',
		'tomato paste',
		'refried beans',
		'black beans',
		'tamarind',
		'chicken stock',
		'beef stock',
		'evaporated milk',
		'sweetened condensed milk',
		
		'new mexico chiles',
		'anaheim chiles',
		'hatch chiles',
		'poblano chiles',
		'ancho chiles',
		'chile negro',
		'serrano chiles',
		'guajillo chiles',
		'pasilla chiles',
		'cascabel chiles',
		
		'pinto beans',
		'black beans',
		'white rice',
		'white rice',
		
		'garlic powder',
		'onion powder',
		'standard chile powder',
		'cumin',
		'oregano',
		'parsley',
		'saffron',
		'cilantro',
		'cinnamon sticks',
		'cloves',
		'bay leaves',
		'achiote',
		'epazote',
		'anise',
		'vanilla',
		'vanilla beans',
		'hoja santa',
		
		'flour tortillas',
		'corn tortillas',
		'white flour',
		'corn meal',
		'masa harina',
		'cornmeal',
		'hominy',
		
		'tomatoes',
		'tomatillos',
		'cilantro',
		'epazote',
		'onion',
		'potatoes',
		'cucumber',
		'parsley',
		'jicama',
		'limes',
		'lemons',
		'green onion',
		'bell pepper',
		'avocado',
		'garlic',
		'plantains',
		
		'jack cheese',
		'queso fresco',
		'queso blanco',
		'queso enchilado',
		'cotija',
		'panela',
		'crema',
		
		'eggs',
		'ground beef',
		'skirt steak',
		'chicken breasts',
		'chicken pieces',
		'whole chicken',
		'veal',
		'lamb',
		'pork loin',
		'pork roast',
		'chorizo',
		'ribs',
		
		'tortilla chips',
		'lard',
		'tequila',
		'vegetable oil',
		'coarse salt',
		'chile sauce',
		'sugar',
		'honey',
		'unsweetened chocolate',
		'mexican chocolate',
		'piloncillo'
]

Chinese[
		
]

Italian[
		'canned tomatoes',
		'dried pasta',
		'arborio rice',
		'flour',
		'cannellini beans',
		'bread crumbs',
		'artichokes',
		'olives',
		'pine nuts',
		'capers',
		'garlic',
		'proscuitto',
		'basil',
		'mozzarella',
		'extra-virgin olive oil',
		'balsamic vinegar',
		'wine',
		'parmesan',
		'sage',
		'thyme',
		'oregano'
]

Indian[]

French[]


